#' gen_response_surf_y: Generate DV under response surface model
#'
#' @param x_data IV data typically generated by gen_response_surf_x
#' @param beta vector of regression weights in the order of x_data
#' @param sigma error variance
#' @param y_name name of y variable
#'
#' @return data frame with x and y variables. 
#' @export
#'
#' @examples 
#' 
#' 
#' 
#' 
#' 
#' 
#' 
gen_response_surf_y<-function(x_data, beta, sigma=NULL, y_name=NULL){
  
  if(is.null(y_name)){
    y_name<-"y"
  }
  
  if(is.null(sigma)){
    eps<-0
  }else{
    eps<-rnorm(nrow(x_data), 0, sigma)
  }
  
  x_data[y_name]<-as.vector(as.matrix(x_data)%*%beta+eps)
  
  
  x_data
}
